#!/usr/bin/env python3
"""
MCP Server Template
Use this as a starting point for building Model Context Protocol servers

Generated by Context Foundry
"""
import sys
import json
from typing import Optional, Dict, Any

try:
    from fastmcp import FastMCP
except ImportError:
    print("❌ Error: FastMCP not installed", file=sys.stderr)
    print("", file=sys.stderr)
    print("Install with: pip install fastmcp>=2.0.0", file=sys.stderr)
    sys.exit(1)

# Create MCP server instance
# Change the name to match your server's purpose
mcp = FastMCP("My MCP Server")


# ============================================================================
# TOOLS - Define your tools here using @mcp.tool() decorator
# ============================================================================

@mcp.tool()
def hello(name: str) -> str:
    """
    Say hello to someone.

    This docstring becomes the tool description that the LLM sees.
    Be clear and specific about what the tool does.

    Args:
        name: The name of the person to greet

    Returns:
        A friendly greeting message
    """
    return f"Hello, {name}! Welcome to this MCP server."


@mcp.tool()
def calculate(operation: str, a: float, b: float) -> str:
    """
    Perform a calculation on two numbers.

    Args:
        operation: The operation to perform (add, subtract, multiply, divide)
        a: First number
        b: Second number

    Returns:
        JSON string with the result or error
    """
    try:
        result = None
        if operation == "add":
            result = a + b
        elif operation == "subtract":
            result = a - b
        elif operation == "multiply":
            result = a * b
        elif operation == "divide":
            if b == 0:
                return json.dumps({"error": "Cannot divide by zero"}, indent=2)
            result = a / b
        else:
            return json.dumps({"error": f"Unknown operation: {operation}"}, indent=2)

        return json.dumps({
            "operation": operation,
            "a": a,
            "b": b,
            "result": result
        }, indent=2)

    except Exception as e:
        return json.dumps({"error": str(e)}, indent=2)


@mcp.tool()
async def fetch_data(url: str) -> str:
    """
    Fetch data from a URL (async example).

    This demonstrates an async tool for I/O operations.

    Args:
        url: The URL to fetch

    Returns:
        JSON string with the response
    """
    try:
        # Note: You'll need to install httpx: pip install httpx
        import httpx

        async with httpx.AsyncClient() as client:
            response = await client.get(url)
            response.raise_for_status()

            return json.dumps({
                "status": response.status_code,
                "url": url,
                "content_type": response.headers.get("content-type"),
                "content_length": len(response.content),
                "preview": response.text[:200]  # First 200 chars
            }, indent=2)

    except Exception as e:
        return json.dumps({"error": str(e)}, indent=2)


@mcp.tool()
def get_server_info() -> str:
    """
    Get information about this MCP server.

    Returns:
        JSON string with server capabilities and status
    """
    return json.dumps({
        "name": "My MCP Server",
        "version": "1.0.0",
        "status": "running",
        "capabilities": {
            "tools": ["hello", "calculate", "fetch_data", "get_server_info"],
            "resources": ["data://example"],
            "async_support": True
        },
        "description": "A template MCP server for building custom tools"
    }, indent=2)


# ============================================================================
# RESOURCES - Define resources using @mcp.resource() decorator
# ============================================================================

@mcp.resource("data://example")
def get_example_data() -> str:
    """
    Provide example data as a resource.

    Resources are read-only data sources that can be accessed by URI.
    """
    return json.dumps({
        "examples": [
            {"id": 1, "name": "Example 1", "value": 100},
            {"id": 2, "name": "Example 2", "value": 200},
            {"id": 3, "name": "Example 3", "value": 300}
        ]
    }, indent=2)


# ============================================================================
# PROMPTS - Define prompt templates (optional)
# ============================================================================

# Uncomment to add prompt templates
# @mcp.prompt()
# def example_prompt(topic: str) -> str:
#     """
#     Generate a prompt about a topic.
#     """
#     return f"Please explain {topic} in simple terms."


# ============================================================================
# MAIN - Server startup
# ============================================================================

if __name__ == "__main__":
    # Log server info to stderr (stdout is reserved for MCP protocol)
    print("", file=sys.stderr)
    print("🚀 MCP Server Starting", file=sys.stderr)
    print("", file=sys.stderr)
    print("📋 Available tools:", file=sys.stderr)
    print("   - hello: Say hello to someone", file=sys.stderr)
    print("   - calculate: Perform calculations", file=sys.stderr)
    print("   - fetch_data: Fetch data from URLs (async)", file=sys.stderr)
    print("   - get_server_info: Get server information", file=sys.stderr)
    print("", file=sys.stderr)
    print("📊 Resources:", file=sys.stderr)
    print("   - data://example: Example data source", file=sys.stderr)
    print("", file=sys.stderr)
    print("💡 Configure in Claude Desktop to use this server!", file=sys.stderr)
    print("", file=sys.stderr)

    # Run the MCP server
    # This uses stdio transport (standard for Claude Desktop)
    mcp.run()
