# Pattern Library Configuration

extraction:
  # Minimum cyclomatic complexity for function extraction
  min_complexity: 3

  # Minimum lines of code
  min_lines: 5

  # Deduplication threshold (0-1, higher = more similar required)
  max_similarity: 0.9

  # Supported languages
  languages:
    - python
    - javascript
    - typescript

  # Supported frameworks
  frameworks:
    - fastapi
    - flask
    - django
    - react
    - express
    - nextjs

search:
  # Default number of patterns to return
  default_limit: 5

  # Minimum relevance threshold (0-1)
  min_relevance: 0.6

injection:
  # Enable pattern injection
  enabled: true

  # Maximum patterns to inject per prompt
  max_patterns: 3

  # Only inject patterns with this success rate or higher (%)
  min_success_rate: 70

  # Minimum relevance for injection (0-1)
  min_relevance: 0.6
