# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import (
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__,
)


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(
        self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[
            typing.Union[
                baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]
            ]
        ] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[
            typing.Callable[[str, baml_py.baml_py.FunctionLog], None]
        ] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
        return self.__stream_client

    @property
    def request(self):
        return self.__http_request

    @property
    def stream_request(self):
        return self.__http_stream_request

    @property
    def parse(self):
        return self.__llm_response_parser

    @property
    def parse_stream(self):
        return self.__llm_stream_parser

    async def CreateBuildPlan(
        self,
        architecture_summary: str,
        scout_parallel_recommendation: bool,
        scout_reasoning: str,
        project_type: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BuildPlan:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.CreateBuildPlan(
                architecture_summary=architecture_summary,
                scout_parallel_recommendation=scout_parallel_recommendation,
                scout_reasoning=scout_reasoning,
                project_type=project_type,
                baml_options=baml_options,
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="CreateBuildPlan",
                args={
                    "architecture_summary": architecture_summary,
                    "scout_parallel_recommendation": scout_parallel_recommendation,
                    "scout_reasoning": scout_reasoning,
                    "project_type": project_type,
                },
            )
            return typing.cast(
                types.BuildPlan,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def CreatePhaseInfo(
        self,
        session_id: str,
        phase: types.PhaseType,
        status: types.PhaseStatus,
        detail: str,
        iteration: int,
        baml_options: BamlCallOptions = {},
    ) -> types.PhaseInfo:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.CreatePhaseInfo(
                session_id=session_id,
                phase=phase,
                status=status,
                detail=detail,
                iteration=iteration,
                baml_options=baml_options,
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="CreatePhaseInfo",
                args={
                    "session_id": session_id,
                    "phase": phase,
                    "status": status,
                    "detail": detail,
                    "iteration": iteration,
                },
            )
            return typing.cast(
                types.PhaseInfo,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExecuteBuildTask(
        self,
        task_id: str,
        task_description: str,
        files_to_create: typing.List[str],
        architecture: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BuildTaskResult:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExecuteBuildTask(
                task_id=task_id,
                task_description=task_description,
                files_to_create=files_to_create,
                architecture=architecture,
                baml_options=baml_options,
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExecuteBuildTask",
                args={
                    "task_id": task_id,
                    "task_description": task_description,
                    "files_to_create": files_to_create,
                    "architecture": architecture,
                },
            )
            return typing.cast(
                types.BuildTaskResult,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ExtractPatterns(
        self,
        transcript_text: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Pattern"]:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractPatterns(
                transcript_text=transcript_text, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ExtractPatterns",
                args={
                    "transcript_text": transcript_text,
                },
            )
            return typing.cast(
                typing.List["types.Pattern"],
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def GenerateArchitecture(
        self,
        scout_report_json: str,
        flagged_risks: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.ArchitectureBlueprint:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.GenerateArchitecture(
                scout_report_json=scout_report_json,
                flagged_risks=flagged_risks,
                baml_options=baml_options,
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="GenerateArchitecture",
                args={
                    "scout_report_json": scout_report_json,
                    "flagged_risks": flagged_risks,
                },
            )
            return typing.cast(
                types.ArchitectureBlueprint,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def GenerateScoutReport(
        self,
        task_description: str,
        codebase_analysis: str,
        past_patterns: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ScoutReport:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.GenerateScoutReport(
                task_description=task_description,
                codebase_analysis=codebase_analysis,
                past_patterns=past_patterns,
                baml_options=baml_options,
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="GenerateScoutReport",
                args={
                    "task_description": task_description,
                    "codebase_analysis": codebase_analysis,
                    "past_patterns": past_patterns,
                },
            )
            return typing.cast(
                types.ScoutReport,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ParseArchitectureMarkdown(
        self,
        markdown_content: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ArchitectureBlueprint:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ParseArchitectureMarkdown(
                markdown_content=markdown_content, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ParseArchitectureMarkdown",
                args={
                    "markdown_content": markdown_content,
                },
            )
            return typing.cast(
                types.ArchitectureBlueprint,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ParseScoutMarkdown(
        self,
        markdown_content: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ScoutReport:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ParseScoutMarkdown(
                markdown_content=markdown_content, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ParseScoutMarkdown",
                args={
                    "markdown_content": markdown_content,
                },
            )
            return typing.cast(
                types.ScoutReport,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ValidateBuildResult(
        self,
        result_json: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BuildTaskResult:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ValidateBuildResult(
                result_json=result_json, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ValidateBuildResult",
                args={
                    "result_json": result_json,
                },
            )
            return typing.cast(
                types.BuildTaskResult,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    async def ValidatePhaseInfo(
        self,
        json_string: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PhaseInfo:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ValidatePhaseInfo(
                json_string=json_string, baml_options=baml_options
            )
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(
                baml_options
            ).call_function_async(
                function_name="ValidatePhaseInfo",
                args={
                    "json_string": json_string,
                },
            )
            return typing.cast(
                types.PhaseInfo,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CreateBuildPlan(
        self,
        architecture_summary: str,
        scout_parallel_recommendation: bool,
        scout_reasoning: str,
        project_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.BuildPlan, types.BuildPlan]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="CreateBuildPlan",
            args={
                "architecture_summary": architecture_summary,
                "scout_parallel_recommendation": scout_parallel_recommendation,
                "scout_reasoning": scout_reasoning,
                "project_type": project_type,
            },
        )
        return baml_py.BamlStream[stream_types.BuildPlan, types.BuildPlan](
            result,
            lambda x: typing.cast(
                stream_types.BuildPlan,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.BuildPlan,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def CreatePhaseInfo(
        self,
        session_id: str,
        phase: types.PhaseType,
        status: types.PhaseStatus,
        detail: str,
        iteration: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PhaseInfo, types.PhaseInfo]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="CreatePhaseInfo",
            args={
                "session_id": session_id,
                "phase": phase,
                "status": status,
                "detail": detail,
                "iteration": iteration,
            },
        )
        return baml_py.BamlStream[stream_types.PhaseInfo, types.PhaseInfo](
            result,
            lambda x: typing.cast(
                stream_types.PhaseInfo,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.PhaseInfo,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExecuteBuildTask(
        self,
        task_id: str,
        task_description: str,
        files_to_create: typing.List[str],
        architecture: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.BuildTaskResult, types.BuildTaskResult]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExecuteBuildTask",
            args={
                "task_id": task_id,
                "task_description": task_description,
                "files_to_create": files_to_create,
                "architecture": architecture,
            },
        )
        return baml_py.BamlStream[stream_types.BuildTaskResult, types.BuildTaskResult](
            result,
            lambda x: typing.cast(
                stream_types.BuildTaskResult,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.BuildTaskResult,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractPatterns(
        self,
        transcript_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[
        typing.List["stream_types.Pattern"], typing.List["types.Pattern"]
    ]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ExtractPatterns",
            args={
                "transcript_text": transcript_text,
            },
        )
        return baml_py.BamlStream[
            typing.List["stream_types.Pattern"], typing.List["types.Pattern"]
        ](
            result,
            lambda x: typing.cast(
                typing.List["stream_types.Pattern"],
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                typing.List["types.Pattern"],
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def GenerateArchitecture(
        self,
        scout_report_json: str,
        flagged_risks: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[
        stream_types.ArchitectureBlueprint, types.ArchitectureBlueprint
    ]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="GenerateArchitecture",
            args={
                "scout_report_json": scout_report_json,
                "flagged_risks": flagged_risks,
            },
        )
        return baml_py.BamlStream[
            stream_types.ArchitectureBlueprint, types.ArchitectureBlueprint
        ](
            result,
            lambda x: typing.cast(
                stream_types.ArchitectureBlueprint,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.ArchitectureBlueprint,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def GenerateScoutReport(
        self,
        task_description: str,
        codebase_analysis: str,
        past_patterns: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ScoutReport, types.ScoutReport]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="GenerateScoutReport",
            args={
                "task_description": task_description,
                "codebase_analysis": codebase_analysis,
                "past_patterns": past_patterns,
            },
        )
        return baml_py.BamlStream[stream_types.ScoutReport, types.ScoutReport](
            result,
            lambda x: typing.cast(
                stream_types.ScoutReport,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.ScoutReport,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ParseArchitectureMarkdown(
        self,
        markdown_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[
        stream_types.ArchitectureBlueprint, types.ArchitectureBlueprint
    ]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ParseArchitectureMarkdown",
            args={
                "markdown_content": markdown_content,
            },
        )
        return baml_py.BamlStream[
            stream_types.ArchitectureBlueprint, types.ArchitectureBlueprint
        ](
            result,
            lambda x: typing.cast(
                stream_types.ArchitectureBlueprint,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.ArchitectureBlueprint,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ParseScoutMarkdown(
        self,
        markdown_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ScoutReport, types.ScoutReport]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ParseScoutMarkdown",
            args={
                "markdown_content": markdown_content,
            },
        )
        return baml_py.BamlStream[stream_types.ScoutReport, types.ScoutReport](
            result,
            lambda x: typing.cast(
                stream_types.ScoutReport,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.ScoutReport,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ValidateBuildResult(
        self,
        result_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.BuildTaskResult, types.BuildTaskResult]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ValidateBuildResult",
            args={
                "result_json": result_json,
            },
        )
        return baml_py.BamlStream[stream_types.BuildTaskResult, types.BuildTaskResult](
            result,
            lambda x: typing.cast(
                stream_types.BuildTaskResult,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.BuildTaskResult,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ValidatePhaseInfo(
        self,
        json_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PhaseInfo, types.PhaseInfo]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(
            function_name="ValidatePhaseInfo",
            args={
                "json_string": json_string,
            },
        )
        return baml_py.BamlStream[stream_types.PhaseInfo, types.PhaseInfo](
            result,
            lambda x: typing.cast(
                stream_types.PhaseInfo,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.PhaseInfo,
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )


class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def CreateBuildPlan(
        self,
        architecture_summary: str,
        scout_parallel_recommendation: bool,
        scout_reasoning: str,
        project_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="CreateBuildPlan",
            args={
                "architecture_summary": architecture_summary,
                "scout_parallel_recommendation": scout_parallel_recommendation,
                "scout_reasoning": scout_reasoning,
                "project_type": project_type,
            },
            mode="request",
        )
        return result

    async def CreatePhaseInfo(
        self,
        session_id: str,
        phase: types.PhaseType,
        status: types.PhaseStatus,
        detail: str,
        iteration: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="CreatePhaseInfo",
            args={
                "session_id": session_id,
                "phase": phase,
                "status": status,
                "detail": detail,
                "iteration": iteration,
            },
            mode="request",
        )
        return result

    async def ExecuteBuildTask(
        self,
        task_id: str,
        task_description: str,
        files_to_create: typing.List[str],
        architecture: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExecuteBuildTask",
            args={
                "task_id": task_id,
                "task_description": task_description,
                "files_to_create": files_to_create,
                "architecture": architecture,
            },
            mode="request",
        )
        return result

    async def ExtractPatterns(
        self,
        transcript_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractPatterns",
            args={
                "transcript_text": transcript_text,
            },
            mode="request",
        )
        return result

    async def GenerateArchitecture(
        self,
        scout_report_json: str,
        flagged_risks: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="GenerateArchitecture",
            args={
                "scout_report_json": scout_report_json,
                "flagged_risks": flagged_risks,
            },
            mode="request",
        )
        return result

    async def GenerateScoutReport(
        self,
        task_description: str,
        codebase_analysis: str,
        past_patterns: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="GenerateScoutReport",
            args={
                "task_description": task_description,
                "codebase_analysis": codebase_analysis,
                "past_patterns": past_patterns,
            },
            mode="request",
        )
        return result

    async def ParseArchitectureMarkdown(
        self,
        markdown_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ParseArchitectureMarkdown",
            args={
                "markdown_content": markdown_content,
            },
            mode="request",
        )
        return result

    async def ParseScoutMarkdown(
        self,
        markdown_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ParseScoutMarkdown",
            args={
                "markdown_content": markdown_content,
            },
            mode="request",
        )
        return result

    async def ValidateBuildResult(
        self,
        result_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ValidateBuildResult",
            args={
                "result_json": result_json,
            },
            mode="request",
        )
        return result

    async def ValidatePhaseInfo(
        self,
        json_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ValidatePhaseInfo",
            args={
                "json_string": json_string,
            },
            mode="request",
        )
        return result


class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def CreateBuildPlan(
        self,
        architecture_summary: str,
        scout_parallel_recommendation: bool,
        scout_reasoning: str,
        project_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="CreateBuildPlan",
            args={
                "architecture_summary": architecture_summary,
                "scout_parallel_recommendation": scout_parallel_recommendation,
                "scout_reasoning": scout_reasoning,
                "project_type": project_type,
            },
            mode="stream",
        )
        return result

    async def CreatePhaseInfo(
        self,
        session_id: str,
        phase: types.PhaseType,
        status: types.PhaseStatus,
        detail: str,
        iteration: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="CreatePhaseInfo",
            args={
                "session_id": session_id,
                "phase": phase,
                "status": status,
                "detail": detail,
                "iteration": iteration,
            },
            mode="stream",
        )
        return result

    async def ExecuteBuildTask(
        self,
        task_id: str,
        task_description: str,
        files_to_create: typing.List[str],
        architecture: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExecuteBuildTask",
            args={
                "task_id": task_id,
                "task_description": task_description,
                "files_to_create": files_to_create,
                "architecture": architecture,
            },
            mode="stream",
        )
        return result

    async def ExtractPatterns(
        self,
        transcript_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ExtractPatterns",
            args={
                "transcript_text": transcript_text,
            },
            mode="stream",
        )
        return result

    async def GenerateArchitecture(
        self,
        scout_report_json: str,
        flagged_risks: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="GenerateArchitecture",
            args={
                "scout_report_json": scout_report_json,
                "flagged_risks": flagged_risks,
            },
            mode="stream",
        )
        return result

    async def GenerateScoutReport(
        self,
        task_description: str,
        codebase_analysis: str,
        past_patterns: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="GenerateScoutReport",
            args={
                "task_description": task_description,
                "codebase_analysis": codebase_analysis,
                "past_patterns": past_patterns,
            },
            mode="stream",
        )
        return result

    async def ParseArchitectureMarkdown(
        self,
        markdown_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ParseArchitectureMarkdown",
            args={
                "markdown_content": markdown_content,
            },
            mode="stream",
        )
        return result

    async def ParseScoutMarkdown(
        self,
        markdown_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ParseScoutMarkdown",
            args={
                "markdown_content": markdown_content,
            },
            mode="stream",
        )
        return result

    async def ValidateBuildResult(
        self,
        result_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ValidateBuildResult",
            args={
                "result_json": result_json,
            },
            mode="stream",
        )
        return result

    async def ValidatePhaseInfo(
        self,
        json_string: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(
            baml_options
        ).create_http_request_async(
            function_name="ValidatePhaseInfo",
            args={
                "json_string": json_string,
            },
            mode="stream",
        )
        return result


b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))
