# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions


class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CreateBuildPlan(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BuildPlan:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="CreateBuildPlan", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.BuildPlan, result)

    def CreatePhaseInfo(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PhaseInfo:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="CreatePhaseInfo", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.PhaseInfo, result)

    def ExecuteBuildTask(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BuildTaskResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExecuteBuildTask", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.BuildTaskResult, result)

    def ExtractPatterns(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Pattern"]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractPatterns", llm_response=llm_response, mode="request"
        )
        return typing.cast(typing.List["types.Pattern"], result)

    def GenerateArchitecture(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ArchitectureBlueprint:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="GenerateArchitecture",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.ArchitectureBlueprint, result)

    def GenerateScoutReport(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ScoutReport:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="GenerateScoutReport",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.ScoutReport, result)

    def ParseArchitectureMarkdown(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ArchitectureBlueprint:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ParseArchitectureMarkdown",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.ArchitectureBlueprint, result)

    def ParseScoutMarkdown(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ScoutReport:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ParseScoutMarkdown",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.ScoutReport, result)

    def ValidateBuildResult(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.BuildTaskResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ValidateBuildResult",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.BuildTaskResult, result)

    def ValidatePhaseInfo(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PhaseInfo:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ValidatePhaseInfo", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.PhaseInfo, result)


class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CreateBuildPlan(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.BuildPlan:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="CreateBuildPlan", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.BuildPlan, result)

    def CreatePhaseInfo(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.PhaseInfo:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="CreatePhaseInfo", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.PhaseInfo, result)

    def ExecuteBuildTask(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.BuildTaskResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExecuteBuildTask", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.BuildTaskResult, result)

    def ExtractPatterns(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.Pattern"]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractPatterns", llm_response=llm_response, mode="stream"
        )
        return typing.cast(typing.List["stream_types.Pattern"], result)

    def GenerateArchitecture(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.ArchitectureBlueprint:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="GenerateArchitecture",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.ArchitectureBlueprint, result)

    def GenerateScoutReport(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.ScoutReport:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="GenerateScoutReport",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.ScoutReport, result)

    def ParseArchitectureMarkdown(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.ArchitectureBlueprint:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ParseArchitectureMarkdown",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.ArchitectureBlueprint, result)

    def ParseScoutMarkdown(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.ScoutReport:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ParseScoutMarkdown", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.ScoutReport, result)

    def ValidateBuildResult(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.BuildTaskResult:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ValidateBuildResult",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.BuildTaskResult, result)

    def ValidatePhaseInfo(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.PhaseInfo:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ValidatePhaseInfo", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.PhaseInfo, result)
