# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel


from . import types

StreamStateValueT = typing.TypeVar("StreamStateValueT")


class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]


# #########################################################################
# Generated classes (15)
# #########################################################################


class AppliedPattern(BaseModel):
    pattern_id: typing.Optional[str] = None
    pattern_name: typing.Optional[str] = None
    reason: typing.Optional[str] = None


class ArchitectureBlueprint(BaseModel):
    system_overview: typing.Optional[str] = None
    file_structure: typing.List["FileStructure"]
    modules: typing.List["ModuleSpec"]
    applied_patterns: typing.List["AppliedPattern"]
    preventive_measures: typing.List[str]
    implementation_steps: typing.List[str]
    test_plan: typing.Optional["TestPlan"] = None
    success_criteria: typing.List[str]


class BuildError(BaseModel):
    file: typing.Optional[str] = None
    line: typing.Optional[int] = None
    message: typing.Optional[str] = None
    severity: typing.Optional[types.ErrorSeverity] = None
    suggestion: typing.Optional[str] = None


class BuildPlan(BaseModel):
    parallel_build_enabled: typing.Optional[bool] = None
    tasks: typing.List["BuildTask"]
    total_estimated_sequential: typing.Optional[int] = None
    total_estimated_parallel: typing.Optional[int] = None
    time_savings_percent: typing.Optional[int] = None


class BuildTask(BaseModel):
    task_id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    working_directory: typing.Optional[str] = None
    agent_instruction: typing.Optional[str] = None
    provider: typing.Optional[types.AgentProvider] = None
    build_commands: typing.List[str]
    dependencies: typing.List[str]
    estimated_duration_minutes: typing.Optional[int] = None


class BuildTaskResult(BaseModel):
    task_id: typing.Optional[str] = None
    description: typing.Optional[str] = None
    status: typing.Optional[types.BuildStatus] = None
    files_created: typing.List[str]
    files_modified: typing.List[str]
    errors: typing.List["BuildError"]
    warnings: typing.List[str]
    success: typing.Optional[bool] = None
    next_steps: typing.List[str]
    duration_seconds: typing.Optional[float] = None


class Challenge(BaseModel):
    description: typing.Optional[str] = None
    severity: typing.Optional[types.Severity] = None
    mitigation: typing.Optional[str] = None


class CommonIssue(BaseModel):
    issue_id: typing.Optional[str] = None
    description: typing.Optional[str] = None
    solution: typing.Optional[str] = None


class FileStructure(BaseModel):
    path: typing.Optional[str] = None
    purpose: typing.Optional[str] = None
    dependencies: typing.List[str]


class ModuleSpec(BaseModel):
    name: typing.Optional[str] = None
    responsibility: typing.Optional[str] = None
    interfaces: typing.List[str]
    dependencies: typing.List[str]


class Pattern(BaseModel):
    pattern_id: typing.Optional[str] = None
    category: typing.Optional[str] = None
    description: typing.Optional[str] = None
    applies_to: typing.List[str]
    node_types: typing.List[str]
    best_practices: typing.List[str]
    anti_patterns: typing.List[str]
    common_issues: typing.List["CommonIssue"]


class PhaseInfo(BaseModel):
    session_id: typing.Optional[str] = None
    current_phase: typing.Optional[types.PhaseType] = None
    phase_number: typing.Optional[str] = None
    status: typing.Optional[types.PhaseStatus] = None
    progress_detail: typing.Optional[str] = None
    test_iteration: typing.Optional[int] = None
    phases_completed: typing.List[types.PhaseType]
    started_at: typing.Optional[str] = None
    last_updated: typing.Optional[str] = None


class ScoutReport(BaseModel):
    executive_summary: typing.Optional[str] = None
    past_learnings_applied: typing.List[str]
    known_risks: typing.List[str]
    key_requirements: typing.List[str]
    tech_stack: typing.Optional["TechStack"] = None
    architecture_recommendations: typing.List[str]
    main_challenges: typing.List["Challenge"]
    testing_approach: typing.Optional[str] = None
    timeline_estimate: typing.Optional[str] = None


class TechStack(BaseModel):
    languages: typing.List[str]
    frameworks: typing.List[str]
    dependencies: typing.List[str]
    justification: typing.Optional[str] = None


class TestPlan(BaseModel):
    unit_tests: typing.List[str]
    integration_tests: typing.List[str]
    e2e_tests: typing.List[str]
    test_framework: typing.Optional[str] = None
    success_criteria: typing.List[str]


# #########################################################################
# Generated type aliases (0)
# #########################################################################
