# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel


CheckT = typing_extensions.TypeVar("CheckT")
CheckName = typing_extensions.TypeVar("CheckName", bound=str)


class Check(BaseModel):
    name: str
    expression: str
    status: str


class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]


def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())


def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))


# #########################################################################
# Generated enums (6)
# #########################################################################


class AgentProvider(str, Enum):
    Claude = "Claude"
    Gemini = "Gemini"


class BuildStatus(str, Enum):
    Success = "Success"
    Partial = "Partial"
    Failed = "Failed"


class ErrorSeverity(str, Enum):
    Error = "Error"
    Warning = "Warning"
    Info = "Info"


class PhaseStatus(str, Enum):
    Analyzing = "Analyzing"
    Researching = "Researching"
    Designing = "Designing"
    Building = "Building"
    Testing = "Testing"
    SelfHealing = "SelfHealing"
    Capturing = "Capturing"
    Documenting = "Documenting"
    Deploying = "Deploying"
    Completed = "Completed"
    Failed = "Failed"


class PhaseType(str, Enum):
    CodebaseAnalysis = "CodebaseAnalysis"
    Scout = "Scout"
    Architect = "Architect"
    Builder = "Builder"
    Test = "Test"
    Screenshot = "Screenshot"
    Documentation = "Documentation"
    Deploy = "Deploy"
    Feedback = "Feedback"
    GitHub = "GitHub"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# #########################################################################
# Generated classes (15)
# #########################################################################


class AppliedPattern(BaseModel):
    pattern_id: str
    pattern_name: str
    reason: str


class ArchitectureBlueprint(BaseModel):
    system_overview: str
    file_structure: typing.List["FileStructure"]
    modules: typing.List["ModuleSpec"]
    applied_patterns: typing.List["AppliedPattern"]
    preventive_measures: typing.List[str]
    implementation_steps: typing.List[str]
    test_plan: "TestPlan"
    success_criteria: typing.List[str]


class BuildError(BaseModel):
    file: str
    line: typing.Optional[int] = None
    message: str
    severity: ErrorSeverity
    suggestion: typing.Optional[str] = None


class BuildPlan(BaseModel):
    parallel_build_enabled: bool
    tasks: typing.List["BuildTask"]
    total_estimated_sequential: int
    total_estimated_parallel: int
    time_savings_percent: int


class BuildTask(BaseModel):
    task_id: str
    name: str
    description: str
    working_directory: str
    agent_instruction: str
    provider: AgentProvider
    build_commands: typing.List[str]
    dependencies: typing.List[str]
    estimated_duration_minutes: int


class BuildTaskResult(BaseModel):
    task_id: str
    description: str
    status: BuildStatus
    files_created: typing.List[str]
    files_modified: typing.List[str]
    errors: typing.List["BuildError"]
    warnings: typing.List[str]
    success: bool
    next_steps: typing.List[str]
    duration_seconds: typing.Optional[float] = None


class Challenge(BaseModel):
    description: str
    severity: Severity
    mitigation: str


class CommonIssue(BaseModel):
    issue_id: str
    description: str
    solution: str


class FileStructure(BaseModel):
    path: str
    purpose: str
    dependencies: typing.List[str]


class ModuleSpec(BaseModel):
    name: str
    responsibility: str
    interfaces: typing.List[str]
    dependencies: typing.List[str]


class Pattern(BaseModel):
    pattern_id: str
    category: str
    description: str
    applies_to: typing.List[str]
    node_types: typing.List[str]
    best_practices: typing.List[str]
    anti_patterns: typing.List[str]
    common_issues: typing.List["CommonIssue"]


class PhaseInfo(BaseModel):
    session_id: str
    current_phase: PhaseType
    phase_number: str
    status: PhaseStatus
    progress_detail: str
    test_iteration: int
    phases_completed: typing.List[PhaseType]
    started_at: str
    last_updated: str


class ScoutReport(BaseModel):
    executive_summary: str
    past_learnings_applied: typing.List[str]
    known_risks: typing.List[str]
    key_requirements: typing.List[str]
    tech_stack: "TechStack"
    architecture_recommendations: typing.List[str]
    main_challenges: typing.List["Challenge"]
    testing_approach: str
    timeline_estimate: str


class TechStack(BaseModel):
    languages: typing.List[str]
    frameworks: typing.List[str]
    dependencies: typing.List[str]
    justification: str


class TestPlan(BaseModel):
    unit_tests: typing.List[str]
    integration_tests: typing.List[str]
    e2e_tests: typing.List[str]
    test_framework: str
    success_criteria: typing.List[str]


# #########################################################################
# Generated type aliases (0)
# #########################################################################
