# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {
    "types.AppliedPattern": types.AppliedPattern,
    "stream_types.AppliedPattern": stream_types.AppliedPattern,
    "types.ArchitectureBlueprint": types.ArchitectureBlueprint,
    "stream_types.ArchitectureBlueprint": stream_types.ArchitectureBlueprint,
    "types.BuildError": types.BuildError,
    "stream_types.BuildError": stream_types.BuildError,
    "types.BuildPlan": types.BuildPlan,
    "stream_types.BuildPlan": stream_types.BuildPlan,
    "types.BuildTask": types.BuildTask,
    "stream_types.BuildTask": stream_types.BuildTask,
    "types.BuildTaskResult": types.BuildTaskResult,
    "stream_types.BuildTaskResult": stream_types.BuildTaskResult,
    "types.Challenge": types.Challenge,
    "stream_types.Challenge": stream_types.Challenge,
    "types.CommonIssue": types.CommonIssue,
    "stream_types.CommonIssue": stream_types.CommonIssue,
    "types.FileStructure": types.FileStructure,
    "stream_types.FileStructure": stream_types.FileStructure,
    "types.ModuleSpec": types.ModuleSpec,
    "stream_types.ModuleSpec": stream_types.ModuleSpec,
    "types.Pattern": types.Pattern,
    "stream_types.Pattern": stream_types.Pattern,
    "types.PhaseInfo": types.PhaseInfo,
    "stream_types.PhaseInfo": stream_types.PhaseInfo,
    "types.ScoutReport": types.ScoutReport,
    "stream_types.ScoutReport": stream_types.ScoutReport,
    "types.TechStack": types.TechStack,
    "stream_types.TechStack": stream_types.TechStack,
    "types.TestPlan": types.TestPlan,
    "stream_types.TestPlan": stream_types.TestPlan,
    "types.AgentProvider": types.AgentProvider,
    "types.BuildStatus": types.BuildStatus,
    "types.ErrorSeverity": types.ErrorSeverity,
    "types.PhaseStatus": types.PhaseStatus,
    "types.PhaseType": types.PhaseType,
    "types.Severity": types.Severity,
}
