/**
 * Type declaration for version.json
 * Generated by scripts/version.js at build time
 */

declare module '*/version.json' {
  interface VersionInfo {
    version: string;
    commitsSinceTag: number;
    commitHash: string;
    isDirty: boolean;
    commitDate: string;
    githubUrl: string;
    buildTime: string;
    displayVersion: string;
  }

  const versionInfo: VersionInfo;
  export default versionInfo;
}
