"""
Phase Metrics - Token counting and metrics logging for per-phase execution.

Implements:
- TokenCounter: Estimate token counts from text
- estimate_context_tokens(): Estimate phase context usage
- log_phase_metrics(): Write metrics to session-summary.json
"""

import json
import sys
from datetime import datetime
from pathlib import Path


class TokenCounter:
    """Estimate token counts from text (rough heuristic)."""

    @staticmethod
    def count_tokens(text: str) -> int:
        """
        Rough token estimation: 1 token ≈ 4 characters.

        This is a heuristic. Actual tokenization varies by model.
        Claude uses ~3.5-4.0 chars/token average.

        Args:
            text: Text to count tokens for

        Returns:
            Estimated token count
        """
        return len(text) // 4

    @staticmethod
    def count_file_tokens(file_path: Path) -> int:
        """
        Count tokens in a file.

        Args:
            file_path: Path to file

        Returns:
            Estimated token count, or 0 if file doesn't exist
        """
        if not file_path.exists():
            return 0

        try:
            content = file_path.read_text(errors="ignore")
            return TokenCounter.count_tokens(content)
        except Exception as e:
            print(f"⚠️  Error reading {file_path}: {e}", file=sys.stderr)
            return 0


def estimate_context_tokens(stdout: str, stderr: str, phase_files: list[Path]) -> int:
    """
    Estimate total context tokens for a phase.

    Context includes:
    - Phase prompt (static, from prompt file)
    - Input files read by phase
    - Output generated by phase
    - Tool outputs in stdout/stderr

    Args:
        stdout: Process stdout
        stderr: Process stderr
        phase_files: Files read/written by phase

    Returns:
        Estimated token count
    """
    total_tokens = 0

    # Count stdout/stderr (contains tool outputs, agent responses)
    total_tokens += TokenCounter.count_tokens(stdout)
    total_tokens += TokenCounter.count_tokens(stderr)

    # Count phase input/output files
    for file_path in phase_files:
        total_tokens += TokenCounter.count_file_tokens(file_path)

    return total_tokens


def log_phase_metrics(
    phase_name: str,
    duration_seconds: float,
    context_tokens: int,
    exit_code: int,
    working_directory: Path,
    iteration: int = 0,
):
    """
    Log phase metrics to session-summary.json.

    Appends to existing session-summary.json or creates new one.
    Follows format from current Context Foundry builds.

    Args:
        phase_name: e.g., "Scout", "Architect", "Builder"
        duration_seconds: How long phase took
        context_tokens: Estimated tokens used
        exit_code: Process exit code (0 = success)
        working_directory: Project directory
        iteration: Test iteration number (for self-healing loop)
    """
    summary_file = working_directory / ".context-foundry" / "session-summary.json"

    # Load existing summary or create new
    if summary_file.exists():
        try:
            with open(summary_file) as f:
                summary = json.load(f)
        except json.JSONDecodeError:
            summary = _create_new_summary()
    else:
        summary = _create_new_summary()

    # Ensure context_metrics structure exists (handles legacy summaries)
    if "context_metrics" not in summary:
        summary["context_metrics"] = {
            "max_context_window": 200000,
            "model": "claude-sonnet-4",
            "by_phase": {},
        }
    elif "by_phase" not in summary["context_metrics"]:
        summary["context_metrics"]["by_phase"] = {}

    # Ensure phases structure exists
    if "phases" not in summary:
        summary["phases"] = {}

    # Calculate context percentage and zone
    max_context = 200000
    percentage = (context_tokens / max_context) * 100

    if percentage < 40:
        zone = "smart"
    elif percentage < 80:
        zone = "dumb"
    else:
        zone = "critical"

    # Budget allocations (from design spec)
    budget_allocation = {
        "Scout": 14000,
        "Architect": 14000,
        "Builder": 40000,
        "Test": 40000,
        "Documentation": 10000,
        "Deploy": 6000,
        "Feedback": 10000,
        "Screenshot": 3000,
        "Integration Pre-Check": 5000,
        "Codebase Analysis": 10000,
        "GitHub Integration": 8000,
    }
    budget = budget_allocation.get(phase_name, 10000)

    # Record phase metrics
    phase_key = f"phase_{phase_name.lower().replace(' ', '_')}"
    if iteration > 0:
        phase_key += f"_iteration_{iteration}"

    summary["context_metrics"]["by_phase"][phase_key] = {
        "tokens_used": context_tokens,
        "percentage": round(percentage, 2),
        "zone": zone,
        "budget_allocated": budget,
        "over_budget": context_tokens > budget,
        "duration_seconds": round(duration_seconds, 2),
        "exit_code": exit_code,
        "timestamp": datetime.now().isoformat(),
    }

    summary["phases"][phase_key] = {
        "status": "completed" if exit_code == 0 else "failed",
        "duration_seconds": round(duration_seconds, 2),
        "timestamp": datetime.now().isoformat(),
    }

    # Save updated summary
    summary_file.parent.mkdir(parents=True, exist_ok=True)
    with open(summary_file, "w") as f:
        json.dump(summary, f, indent=2)

    # Print metrics to console
    print(f"\n{'=' * 60}", file=sys.stderr)
    print(f"PHASE METRICS: {phase_name}", file=sys.stderr)
    print(f"{'=' * 60}", file=sys.stderr)
    print(f"Duration: {duration_seconds:.1f}s", file=sys.stderr)
    print(f"Context: {context_tokens:,} tokens ({percentage:.1f}%)", file=sys.stderr)
    print(f"Zone: {zone.upper()}", file=sys.stderr)
    print(f"Budget: {budget:,} tokens", file=sys.stderr)

    if context_tokens > budget:
        print(f"⚠️  OVER BUDGET by {context_tokens - budget:,} tokens", file=sys.stderr)

    print(f"Status: {'✅ PASS' if exit_code == 0 else '❌ FAIL'}", file=sys.stderr)
    print(f"{'=' * 60}\n", file=sys.stderr)


def _create_new_summary() -> dict:
    """Create new session summary structure."""
    return {
        "build_start": datetime.now().isoformat(),
        "context_metrics": {
            "max_context_window": 200000,
            "model": "claude-sonnet-4",
            "by_phase": {},
        },
        "phases": {},
    }
