# Homebrew formula template for Foundry
# This file is auto-generated by the release workflow.
# Manual edits will be overwritten on the next release.
#
# To install:
#   brew tap context-foundry/tap
#   brew install foundry

class Foundry < Formula
  desc "Autonomous build loop — the engine of Context Foundry"
  homepage "https://github.com/context-foundry/context-foundry"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/context-foundry/context-foundry/releases/download/v0.2.0/foundry-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/context-foundry/context-foundry/releases/download/v0.2.0/foundry-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/context-foundry/context-foundry/releases/download/v0.2.0/foundry-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/context-foundry/context-foundry/releases/download/v0.2.0/foundry-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "foundry"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/foundry --version")
  end
end
